### ISSUE TITLE
Documentation to Contribute

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [ShanikaEdiriweera/image-upload-app#1]
Right now we have not enough documentation to help the contributors and users. A nice Documentation for contribution (CONTRIBUTING.md) would be a great help for the project.

**Comment by pandaa880** [comment]
If it is alright, I would like to work on this.

**Comment by ShanikaEdiriweera** [comment]
> If it is alright, I would like to work on this.

Great :100:

**Comment by pandaa880** [comment]
I have made a PR. 
Review it and let me know if you want to add more..

**Comment by pandaa880** [comment]
I have updated the CONTRIBUTING.md and made a new PR. Please review it.

**Comment by ShanikaEdiriweera** [comment]
Closed with #8
