### ISSUE TITLE
Add And Design UI framework for React app

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [ShanikaEdiriweera/image-upload-app#5]
Right now the react application does not have a UI framework.
It would be nice to have a react UI framework with a nice UI.

**Comment by razi-ed** [comment]
can i claim this issue please?

**Comment by ShanikaEdiriweera** [comment]
> can i claim this issue please?

Great :100:

**Comment by ShanikaEdiriweera** [comment]
@razi-ed how is the progress?

**Comment by ShanikaEdiriweera** [comment]
@razi-ed are you working on this or not?

**Comment by pandaa880** [comment]
If he is not working then, Can I work on this ?

**Comment by ShanikaEdiriweera** [comment]
@pandaa880 That would be great 💯

**Comment by pandaa880** [comment]
I have to properly structure the layout and make it responsive right ?

**Comment by pandaa880** [comment]
@ShanikaEdiriweera 
Hi, I have opened PR for this **enhancement**.  Please review it and let me know for changes.
Sorry if this is bit late. We have a religious festival going on and I love it.

**Comment by ShanikaEdiriweera** [comment]
> @ShanikaEdiriweera
> Hi, I have opened PR for this **enhancement**. Please review it and let me know for changes.
> Sorry if this is bit late. We have a religious festival going on and I love it.

I have merged the PR #10 . But it would be great to have a UI framework like Ant design, react-bootstrap, material or semantic UI. Hence I am keeping this issue open.

**Comment by razi-ed** [comment]
hey, please pardon me for ridiculously late. Please look into #11 PR.

**Comment by razi-ed** [comment]
I have added Antd UI framework. And Made a simple layout too.

**Comment by razi-ed** [comment]
Yes I did

**Comment by ShanikaEdiriweera** [comment]
Closed with #11

**Comment by ShanikaEdiriweera** [comment]
Closed with #11
